### ISSUE TITLE
Dark Mode local storage not working

### ISSUE THREAD

**Issue by adityaagg7** [AbhijeetSingla/component-library#6]
# About
When ever a user toggles dark mode, after that refreshed the page or opens the webpage again, the theme is not saved (can be seen easily if system preferred is light).

# Steps to recreate
1. Set your system preference to light
2. Open page
3. toggle to dark mode
4. refresh or open the webpage again

# Result
**Expected** - Page should load in dark mode
**Actual** - Page loads in light mode

**Comment by AbhijeetSingla** [comment]
kindly do check, also thank you for the report.
# Status
fixed :D
# Issue explanation
The conditions were not defined after the local storage item "darkMode" was set to either "enabled" or "disabled".
# Resolution
A second if-else was added to check for the same.
# Preview
[Live Preview](https://as1553-component-library.netlify.app)
